version: '3.8'

services:
  deeplearning_lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10MB"
        max-file: "10"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deeplearning_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10MB"
        max-file: "10"

volumes:
  pgdata:
